name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        # Builder instance
        # builder: # optional
        # Build's context is the set of files located in the specified PATH or URL
        # context: # optional
        # Path to the Dockerfile
        # file: # optional
        # List of build-time variables
        # build-args: # optional
        # List of metadata for an image
        # labels: # optional
        # List of tags
        tags:  papermc-docker:$(date +%s)
        # Always attempt to pull a newer version of the image
        # pull: # optional, default is false
        # Sets the target stage to build
        # target: # optional
        # List of extra privileged entitlement (eg. network.host,security.insecure)
        # allow: # optional
        # Do not use cache when building the image
        # no-cache: # optional, default is false
        # List of target platforms for build
        # platforms: # optional
        # Load is a shorthand for --output=type=docker
        # load: # optional, default is false
        # Push is a shorthand for --output=type=registry
        push: true
        # List of output destinations (format: type=local,dest=path)
        # outputs: # optional
        # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
        # cache-from: # optional
        # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
        # cache-to: # optional
        # List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
        # secrets: # optional
        # List of secret files to expose to the build (eg. key=filename, MY_SECRET=./secret.txt)
        # secret-files: # optional
        # List of SSH agent socket or keys to expose to the build
        # ssh: # optional
        # GitHub Token used to authenticate against a repository for Git context
        # github-token: # optional, default is ${{ github.token }}
      
    - name: Container image scan
      uses: Azure/container-scan@v0
      with:
        # Docker image to scan
        image-name: papermc-docker:$(date +%s)
        # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
        severity-threshold: HIGH
